
[functions.single-session-invalidator]
enabled = true
verify_jwt = true
import_map = "./functions/single-session-invalidator/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/single-session-invalidator/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/single-session-invalidator/*.html" ]

[functions.enviar-factura]
enabled = true
verify_jwt = true
import_map = "./functions/enviar-factura/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/enviar-factura/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/enviar-factura/*.html" ]
